# Freelancers
freelancers = [{'first_name': 'Nancy', 'last_name': 'Browning', 'position': 'Software Engineer', 'salary': 1482.47, 'salary_per_overtime': 7, 'overtime': 32},
            {'first_name': 'Jennifer', 'last_name': 'Coleman', 'position': 'Data Scientist', 'salary': 1358.54, 'salary_per_overtime': 9, 'overtime': 23},
            {'first_name': 'William', 'last_name': 'Gibbs', 'position': 'DevOps Engineer', 'salary': 1550.05, 'salary_per_overtime': 11, 'overtime': 49},
            {'first_name': 'Briana', 'last_name': 'Sullivan', 'position': 'DevOps Engineer', 'salary': 1314.85, 'salary_per_overtime': 8, 'overtime': 8},
            {'first_name': 'Shane', 'last_name': 'Powers', 'position': 'DevOps Engineer', 'salary': 1310.79, 'salary_per_overtime': 8, 'overtime': 14},
            {'first_name': 'Thomas', 'last_name': 'Hill', 'position': 'UX Designer', 'salary': 1620.75, 'salary_per_overtime': 7, 'overtime': 59},
            {'first_name': 'Melanie', 'last_name': 'Adams', 'position': 'DevOps Engineer', 'salary': 1345.82, 'salary_per_overtime': 9, 'overtime': 6},
            {'first_name': 'Theresa', 'last_name': 'Murillo', 'position': 'Data Scientist', 'salary': 1388.28, 'salary_per_overtime': 7, 'overtime': 45},
            {'first_name': 'Alexander', 'last_name': 'Mitchell', 'position': 'DevOps Engineer', 'salary': 1287.15, 'salary_per_overtime': 10, 'overtime': 7},
            {'first_name': 'Laura', 'last_name': 'Mitchell', 'position': 'DevOps Engineer', 'salary': 1234.84, 'salary_per_overtime': 12, 'overtime': 13},
            {'first_name': 'Madison', 'last_name': 'Rice', 'position': 'UX Designer', 'salary': 1689.09, 'salary_per_overtime': 10, 'overtime': 44},
            {'first_name': 'Jennifer', 'last_name': 'Duncan', 'position': 'Product Manager', 'salary': 1459.7, 'salary_per_overtime': 9, 'overtime': 59},
            {'first_name': 'Allison', 'last_name': 'Stone', 'position': 'UX Designer', 'salary': 1502.51, 'salary_per_overtime': 11, 'overtime': 11},
            {'first_name': 'Tabitha', 'last_name': 'Morris', 'position': 'Product Manager', 'salary': 1596.7, 'salary_per_overtime': 11, 'overtime': 35},
            {'first_name': 'Steven', 'last_name': 'Parks', 'position': 'Product Manager', 'salary': 1207.69, 'salary_per_overtime': 8, 'overtime': 46},
            {'first_name': 'Jessica', 'last_name': 'Black', 'position': 'UX Designer', 'salary': 1339.72, 'salary_per_overtime': 11, 'overtime': 49},
            {'first_name': 'Kimberly', 'last_name': 'Larson', 'position': 'Product Manager', 'salary': 1574.48, 'salary_per_overtime': 7, 'overtime': 50},
            {'first_name': 'Bryan', 'last_name': 'Adams', 'position': 'DevOps Engineer', 'salary': 1283.17, 'salary_per_overtime': 7, 'overtime': 44},
            {'first_name': 'Jennifer', 'last_name': 'Bass', 'position': 'Software Engineer', 'salary': 1398.17, 'salary_per_overtime': 11, 'overtime': 48},
            ]

salaried = [{'first_name': 'Troy', 'last_name': 'May', 'position': 'Software Engineer', 'salary': 1100, 'level': 'Junior'},
            {'first_name': 'Jose', 'last_name': 'Thompson', 'position': 'Product Manager', 'salary': 1100, 'level': 'Junior'},
            {'first_name': 'Crystal', 'last_name': 'Reyes', 'position': 'Product Manager', 'salary': 1100, 'level': 'Director'},
            {'first_name': 'Christopher', 'last_name': 'Thornton', 'position': 'Data Scientist', 'salary': 1100, 'level': 'Junior'},
            {'first_name': 'Hannah', 'last_name': 'Mcintyre', 'position': 'Product Manager', 'salary': 1100, 'level': 'Senior'},
            {'first_name': 'Brent', 'last_name': 'Clarke', 'position': 'Data Scientist', 'salary': 1100, 'level': 'Junior'},
            {'first_name': 'Lori', 'last_name': 'Martinez', 'position': 'UX Designer', 'salary': 1100, 'level': 'Mid'},
            {'first_name': 'Justin', 'last_name': 'Reynolds', 'position': 'Software Engineer', 'salary': 1100, 'level': 'Junior'},
            {'first_name': 'William', 'last_name': 'Yang', 'position': 'Data Scientist', 'salary': 1100, 'level': 'Lead'},
            {'first_name': 'Riley', 'last_name': 'Suarez', 'position': 'UX Designer', 'salary': 1100, 'level': 'Director'},
            {'first_name': 'Christopher', 'last_name': 'Torres', 'position': 'Software Engineer', 'salary': 1100, 'level': 'Lead'},
            {'first_name': 'Richard', 'last_name': 'Eaton', 'position': 'DevOps Engineer', 'salary': 1100, 'level': 'Lead'},
            {'first_name': 'Melissa', 'last_name': 'Palmer', 'position': 'Software Engineer', 'salary': 1100, 'level': 'Junior'},
            {'first_name': 'Christina', 'last_name': 'Barr', 'position': 'UX Designer', 'salary': 1100, 'level': 'Junior'},
            {'first_name': 'Francisco', 'last_name': 'Lee', 'position': 'Product Manager', 'salary': 1100, 'level': 'Mid'},
            {'first_name': 'Jason', 'last_name': 'Gutierrez', 'position': 'DevOps Engineer', 'salary': 11005, 'level': 'Mid'}
            ]

students = [{'first_name': 'Christina', 'last_name': 'Nelson', 'position': 'Software Engineer', 'salary': 0, 'age': 28},
            {'first_name': 'Sandra', 'last_name': 'Beard', 'position': 'Data Scientist', 'salary': 0, 'age': 22},
            {'first_name': 'Tyler', 'last_name': 'Chapman', 'position': 'Software Engineer', 'salary': 0, 'age': 22},
            {'first_name': 'Barbara', 'last_name': 'Wolf', 'position': 'officer', 'salary': 0, 'age': 23},
            {'first_name': 'Lauren', 'last_name': 'Bush', 'position': 'Python', 'salary': 0, 'age': 29},
            {'first_name': 'Melanie', 'last_name': 'Whitaker', 'position': 'Java', 'salary': 0, 'age': 23},
            {'first_name': 'Yvette', 'last_name': 'Walsh', 'position': 'Java', 'salary': 0, 'age': 28},
            {'first_name': 'Marisa', 'last_name': 'White', 'position': 'officer', 'salary': 0, 'age': 30},
            {'first_name': 'Brian', 'last_name': 'Wang', 'position': 'officer', 'salary': 0, 'age': 28},
            {'first_name': 'Kristen', 'last_name': 'Jefferson', 'position': 'Java', 'salary': 0, 'age': 23},
           ]